version: '3'

volumes:
  dbdata:
    driver: local

networks:
  boiderplate-network:
    driver: bridge

services:

  web:
    image: nginx:stable
    container_name: boiderplate-nginx
    ports:
      - "8088:80"
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/boiderplate.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx
    depends_on:
      - php
      - db
    networks:
      - boiderplate-network
#        aliases:
#          - local.boiderplate.com.br

  db:
    image: postgres:12
    container_name: boiderplate-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./.docker/database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: boiderplate
      POSTGRES_ROOT_PASSWORD: boiderplate
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - boiderplate-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boiderplate-php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - boiderplate-network
